name: Ignore
main: net.simpvp.Ignore.Ignore
version: 5
author: simpvp.net
description: Lets players ignore other players.
commands:
  Ignore:
    description: (Un)ignores target player.
  Me:
    description: Duplicate of vanilla /me with ignore support
  Tell:
    description: Duplicate of vanilla /tell with ignore support and with clickable links
  W:
    description: Alias for /tell
  Msg:
    description: Alias for /tell
  M:
    description: Sends a private message to the last person you sent a message to
  R:
    description: Sends a private message to the last person you received a message from
  Servertell:
    description: Sends a private message as Server, only for OPs
